// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1VrObBZR00afeQW1Qvwbylx2KnG3dPqw',
    appId: '1:113601893373:web:6e2c9dbad87aab97c33f94',
    messagingSenderId: '113601893373',
    projectId: 'tradeproof-59cd6',
    authDomain: 'tradeproof-59cd6.firebaseapp.com',
    storageBucket: 'tradeproof-59cd6.firebasestorage.app',
    measurementId: 'G-HW0DNQGKWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqyVCMucV2UqcYPC3NaNwrCQaebwfbNXQ',
    appId: '1:113601893373:android:c7a38eb7ad4ab12ac33f94',
    messagingSenderId: '113601893373',
    projectId: 'tradeproof-59cd6',
    storageBucket: 'tradeproof-59cd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9nVJXyy4q92NV-wnAQ67VKCWCodfmII',
    appId: '1:113601893373:ios:08d7b2208ed77b6bc33f94',
    messagingSenderId: '113601893373',
    projectId: 'tradeproof-59cd6',
    storageBucket: 'tradeproof-59cd6.firebasestorage.app',
    iosBundleId: 'com.example.tradeProof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj9nVJXyy4q92NV-wnAQ67VKCWCodfmII',
    appId: '1:113601893373:ios:08d7b2208ed77b6bc33f94',
    messagingSenderId: '113601893373',
    projectId: 'tradeproof-59cd6',
    storageBucket: 'tradeproof-59cd6.firebasestorage.app',
    iosBundleId: 'com.example.tradeProof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1VrObBZR00afeQW1Qvwbylx2KnG3dPqw',
    appId: '1:113601893373:web:e32c86ec99c70fccc33f94',
    messagingSenderId: '113601893373',
    projectId: 'tradeproof-59cd6',
    authDomain: 'tradeproof-59cd6.firebaseapp.com',
    storageBucket: 'tradeproof-59cd6.firebasestorage.app',
    measurementId: 'G-5YQZJCB4Q4',
  );
}
